In [3]:
import torch

In [10]:
atom_types = torch.randint(0, 5, (10, ))

In [11]:
atom_types

tensor([1, 2, 0, 4, 4, 4, 0, 3, 1, 3])

In [12]:
atom_idx = torch.tensor([0,0,0,0,0,1,1,1,1,1])

In [19]:
import torch

# Sample data
# atom_types = torch.randint(0, 5, (10,))  # Random integers in [0, 5)
atom_idx = torch.tensor([0, 0, 0, 0, 0, 1, 1, 1, 1, 1])  # Group indices

# Step 1: Get unique indices and the number of unique groups
unique_indices, inverse_indices = torch.unique(atom_idx, return_inverse=True)

# Step 2: Compute the mode for each group
max_type = atom_types.max().item() + 1  # Maximum possible type + 1 for safe indexing
histogram = torch.zeros((unique_indices.size(0), max_type), dtype=torch.long)

# Count occurrences of each type in each group
histogram.scatter_add_(1, atom_types.unsqueeze(0), torch.ones_like(atom_types).unsqueeze(0))

# Get the most frequent element (mode) per group
mode_values = torch.argmax(histogram, dim=1)

# Step 3: Map back to original atom_idx positions
filled_atom_types = mode_values[inverse_indices]

print(filled_atom_types)

tensor([4, 4, 4, 4, 4, 0, 0, 0, 0, 0])


In [22]:
import torch_scatter

In [26]:
torch.functional.F.one_hot(atom_types)

tensor([[0, 1, 0, 0, 0],
        [0, 0, 0, 1, 0],
        [1, 0, 0, 0, 0],
        [0, 0, 0, 0, 1],
        [0, 1, 0, 0, 0],
        [0, 0, 0, 0, 1],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 0, 1],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 0, 1]])

In [31]:
freq = torch_scatter.scatter(torch.functional.F.one_hot(atom_types), atom_idx, dim=0, reduce='sum')

In [32]:
freq

tensor([[1, 2, 0, 1, 1],
        [0, 0, 2, 0, 3]])

In [24]:
torch_scatter.scatter_max(torch.functional.F.one_hot(atom_types), atom_idx, dim=0)

(tensor([[1, 1, 0, 1, 1],
         [0, 0, 1, 0, 1]]),
 tensor([[2, 0, 0, 1, 3],
         [5, 5, 6, 5, 5]]))

In [33]:
torch.argmax(freq, dim=1)[atom_idx]

tensor([1, 1, 1, 1, 1, 4, 4, 4, 4, 4])