In [1]:
import sys
import os
from pathlib import Path
sys.path.append(Path.cwd().parent.as_posix())
from util import *
from visualizer import visualizer
vis = visualizer()

In [2]:
structures = test_structures()

[I] Loaded 100 structures


In [48]:
st = structures[2]

In [6]:
st

Structure Summary
Lattice
    abc : 5.037987 6.466845720000001 6.466846110061702
 angles : 78.7724752643975 67.07509394860574 67.07510212
 volume : 178.4919011563086
      A : -4.640067767280082 0.0 -1.9624179287851597
      B : -2.4375745524822383 -5.948420913767813 -0.7032869258155185
      C : -4.640067767280082 0.0 4.504427791214841
    pbc : True True True
PeriodicSite: Y0 (Y) (0.0, 0.0, 0.0) [0.0, 0.0, 0.0]
PeriodicSite: Ga1 (Ga) (-8.938, -4.826, 1.732) [0.6888, 0.8112, 0.8112]
PeriodicSite: Ga2 (Ga) (-2.78, -1.123, 0.1068) [0.3112, 0.1888, 0.1888]
PeriodicSite: Ga3 (Ga) (-3.889, -2.03, 2.728) [0.0, 0.3412, 0.6588]
PeriodicSite: Ga4 (Ga) (-3.189, -3.919, 1.074) [0.0, 0.6588, 0.3412]
PeriodicSite: Ga5 (Ga) (-6.235, -3.891, 1.808) [0.3459, 0.6541, 0.6541]
PeriodicSite: Ga6 (Ga) (-5.483, -2.057, 0.03102) [0.6541, 0.3459, 0.3459]
PeriodicSite: Co7 (Co) (-2.32, 0.0, 2.252) [2.22e-16, 0.0, 0.5]
PeriodicSite: Co8 (Co) (-8.179, -2.974, 3.172) [0.5, 0.5, 1.0]
PeriodicSite: Co9 (Co) (-1.21

In [7]:
res = test_space_group_projection(st)

In [10]:
res["proj_structure"].get_primitive_structure()

Structure Summary
Lattice
    abc : 7.072781932639566 7.072781932639566 7.072781932639566
 angles : 101.93479982161779 109.21506077989316 117.65112825004546
 volume : 267.20768258861386
      A : -4.454172611236572 -4.096371650695801 -3.6611924171447754
      B : 4.454172611236572 4.096371650695801 -3.6611924171447754
      C : 4.454172611236572 -4.096371650695801 3.6611924171447754
    pbc : True True True
PeriodicSite: Co (-2.227, -2.048, -1.831) [0.5, 0.0, 0.0]
PeriodicSite: Co (2.227, 2.048, -1.831) [0.0, 0.5, 0.0]
PeriodicSite: Co (2.227, -2.048, 1.831) [0.0, 0.0, 0.5]
PeriodicSite: Co (2.227, -2.048, -1.831) [0.5, 0.5, 0.5]
PeriodicSite: Co (2.22e-16, -2.279, -3.661) [0.7782, 0.5, 0.2782]
PeriodicSite: Co (4.454, -1.817, 0.0) [0.2218, 0.5, 0.7218]
PeriodicSite: Ga (4.454, 0.0, -1.791) [0.2446, 0.7446, 0.5]
PeriodicSite: Ga (4.441e-16, -4.096, -1.87) [0.7554, 0.2554, 0.5]
PeriodicSite: Ga (0.0, -1.843, 0.0) [0.225, 0.0, 0.225]
PeriodicSite: Ga (0.0, -6.349, 0.0) [0.775, 0.0, 0.775

In [11]:
res["proj_structure"]

Structure Summary
Lattice
    abc : 8.908345222473145 8.192743301391602 7.322384834289551
 angles : 90.0 90.0 90.0
 volume : 534.4153651772277
      A : 8.908345222473145 0.0 0.0
      B : 0.0 8.192743301391602 0.0
      C : 0.0 0.0 7.322384834289551
    pbc : True True True
PeriodicSite: Y (0.0, 0.0, 0.0) [0.0, 0.0, 0.0]
PeriodicSite: Y (4.454, 4.096, 3.661) [0.5, 0.5, 0.5]
PeriodicSite: Ga (4.454, 0.0, 5.531) [0.5, 0.0, 0.7554]
PeriodicSite: Ga (4.454, 0.0, 1.791) [0.5, 0.0, 0.2446]
PeriodicSite: Ga (0.0, 4.096, 1.87) [0.0, 0.5, 0.2554]
PeriodicSite: Ga (0.0, 4.096, 5.452) [0.0, 0.5, 0.7446]
PeriodicSite: Ga (0.0, 6.349, 0.0) [0.0, 0.775, 0.0]
PeriodicSite: Ga (0.0, 1.843, 0.0) [0.0, 0.225, 0.0]
PeriodicSite: Ga (4.454, 2.253, 3.661) [0.5, 0.275, 0.5]
PeriodicSite: Ga (4.454, 5.94, 3.661) [0.5, 0.725, 0.5]
PeriodicSite: Ga (0.0, 0.0, 2.366) [0.0, 0.0, 0.3231]
PeriodicSite: Ga (0.0, 0.0, 4.957) [0.0, 0.0, 0.6769]
PeriodicSite: Ga (4.454, 4.096, 6.027) [0.5, 0.5, 0.8231]
PeriodicSite: 

In [54]:
tt = SpacegroupAnalyzer(st)
sd = tt.get_symmetry_dataset()
prim = tt.get_primitive_standard_structure()
conv = tt.get_conventional_standard_structure()
conv_to_prim = tt.get_conventional_to_primitive_transformation_matrix()
prim_to_conv = np.linalg.inv(conv_to_prim)
sgn = tt.get_space_group_number()

In [55]:
prim

Structure Summary
Lattice
    abc : 5.456484 5.550569 9.475464738856905
 angles : 90.0 125.08859689766035 90.0
 volume : 234.8250537411465
      A : 0.0 5.456484 0.0
      B : 5.550569 0.0 0.0
      C : 0.0 -5.446898997010619 -7.75343300310806
    pbc : True True True
PeriodicSite: Na (1.255, 0.03127, -5.816) [0.7545, 0.2261, 0.7501]
PeriodicSite: Na (4.295, 2.755, -1.939) [0.7545, 0.7739, 0.2501]
PeriodicSite: Ca (3.913, -2.791, -5.815) [0.2372, 0.705, 0.75]
PeriodicSite: Ca (1.638, -0.06754, -1.938) [0.2372, 0.295, 0.25]
PeriodicSite: Ta (1.354, 2.696, -0.001737) [0.4943, 0.244, 0.000224]
PeriodicSite: Ta (4.196, -0.02779, -3.878) [0.4943, 0.756, 0.5002]
PeriodicSite: Ti (1.36, 2.698, -3.9) [0.9967, 0.245, 0.503]
PeriodicSite: Ti (4.191, 5.422, -0.0236) [0.9967, 0.755, 0.003044]
PeriodicSite: O (4.065, 0.4105, -1.923) [0.3228, 0.7323, 0.2481]
PeriodicSite: O (2.608, 1.223, -4.17) [0.761, 0.4699, 0.5379]
PeriodicSite: O (2.603, -4.248, -7.451) [0.1809, 0.469, 0.961]
PeriodicSite: O (5

In [56]:
conv

Structure Summary
Lattice
    abc : 5.456484 5.550569 9.475464738856905
 angles : 90.0 125.08859689766035 90.0
 volume : 234.8250537411465
      A : 0.0 5.456484 0.0
      B : 5.550569 0.0 0.0
      C : 0.0 -5.446898997010619 -7.75343300310806
    pbc : True True True
PeriodicSite: Na (1.255, 0.03127, -5.816) [0.7545, 0.2261, 0.7501]
PeriodicSite: Na (4.295, 2.755, -1.939) [0.7545, 0.7739, 0.2501]
PeriodicSite: Ca (3.913, -2.791, -5.815) [0.2372, 0.705, 0.75]
PeriodicSite: Ca (1.638, -0.06754, -1.938) [0.2372, 0.295, 0.25]
PeriodicSite: Ta (1.354, 2.696, -0.001737) [0.4943, 0.244, 0.000224]
PeriodicSite: Ta (4.196, -0.02779, -3.878) [0.4943, 0.756, 0.5002]
PeriodicSite: Ti (1.36, 2.698, -3.9) [0.9967, 0.245, 0.503]
PeriodicSite: Ti (4.191, 5.422, -0.0236) [0.9967, 0.755, 0.003044]
PeriodicSite: O (4.065, 0.4105, -1.923) [0.3228, 0.7323, 0.2481]
PeriodicSite: O (2.608, 1.223, -4.17) [0.761, 0.4699, 0.5379]
PeriodicSite: O (2.603, -4.248, -7.451) [0.1809, 0.469, 0.961]
PeriodicSite: O (5

In [59]:
project_random_lattice_to_symmetry(conv.lattice.matrix, conv_to_prim, sgn)

array([[ 5.04447889,  0.        , -2.08000994],
       [ 0.        ,  5.5505681 ,  0.        ],
       [-2.08000994,  0.        ,  9.24434757]])

In [61]:
project_random_lattice_to_symmetry(prim.lattice.matrix, conv_to_prim, sgn, inp_prim=True, out_prim=False)

array([[ 5.04447889,  0.        , -2.08000994],
       [ 0.        ,  5.5505681 ,  0.        ],
       [-2.08000994,  0.        ,  9.24434757]])

In [86]:
def test_project_lattice(struct):
    sga = SpacegroupAnalyzer(struct)
    prim = sga.get_primitive_standard_structure()
    conv = sga.get_conventional_standard_structure()
    conv_to_prim = sga.get_conventional_to_primitive_transformation_matrix()
    # prim_to_conv = np.linalg.inv(conv_to_prim)
    sgn = sga.get_space_group_number()

    prim_lat = prim.lattice.matrix
    conv_lat = conv.lattice.matrix
    res1 = project_random_lattice_to_symmetry(
        conv_lat, conv_to_prim, sgn, inp_prim=False, out_prim=True
    )
    res2 = project_random_lattice_to_symmetry(
        prim_lat, conv_to_prim, sgn, inp_prim=True, out_prim=False
    )
    # print(res1)
    # print(res2)
    return (
        np.allclose(np.array(Lattice(res1).parameters),np.array(prim.lattice.parameters)),
        np.allclose(np.array(Lattice(res2).parameters),np.array(conv.lattice.parameters)),
    )

In [71]:
test_project_lattice(structures[1])

(False,
 False,
 array([[ 5.1365881 ,  3.66215134, -0.64569664],
        [-5.1365881 ,  3.66215134,  0.64569664],
        [-1.29139316,  0.        ,  6.85062027]]),
 array([[10.27317619,  0.        , -1.29139328],
        [ 0.        ,  7.32430267,  0.        ],
        [-1.29139316,  0.        ,  6.85062027]]))

In [50]:
project_random_lattice_to_symmetry(conv.lattice.matrix, conv_to_prim, sgn, inp_prim=False, out_prim=False)

array([[ 5.04447889,  0.        , -2.08000994],
       [ 0.        ,  5.5505681 ,  0.        ],
       [-2.08000994,  0.        ,  9.24434757]])

In [178]:
SpacegroupAnalyzer(prim).get_symmetrized_structure()

SymmetrizedStructure
Full Formula (Y1 Ga6 Co6)
Reduced Formula: Y(GaCo)6
Spacegroup: Immm (71)
abc   :   6.466846   6.466846   6.466846
angles: 134.150196 101.227525  96.243422
Sites (13)
  #  SP           a         b         c  Wyckoff
---  ----  --------  --------  --------  ---------
  0  Y     0         0         0         1a
  1  Ga    0.811228  0.311228  0.5       2j
  2  Ga    0.658796  0         0.658796  2g
  3  Ga    0.65413   0.65413   0         2i
  4  Co    0.5       0         0         4k
  5  Co    0.23856   0.5       0.73856   2h

In [179]:
res = test_space_group_projection(st)

In [180]:
res["proj_structure"]

Structure Summary
Lattice
    abc : 5.510850429534912 7.5926103591918945 6.340409278869629
 angles : 90.0 90.0 90.0
 volume : 265.29375691568094
      A : 5.510850429534912 0.0 0.0
      B : 0.0 7.5926103591918945 0.0
      C : 0.0 0.0 6.340409278869629
    pbc : True True True
PeriodicSite: Y (0.0, 0.0, 0.0) [0.0, 0.0, 0.0]
PeriodicSite: Y (2.755, 3.796, 3.17) [0.5, 0.5, 0.5]
PeriodicSite: Ga (2.755, 0.0, 4.319) [0.5, 0.0, 0.6811]
PeriodicSite: Ga (2.755, 0.0, 2.022) [0.5, 0.0, 0.3189]
PeriodicSite: Ga (0.0, 3.796, 1.148) [0.0, 0.5, 0.1811]
PeriodicSite: Ga (0.0, 3.796, 5.192) [0.0, 0.5, 0.8189]
PeriodicSite: Ga (0.0, 5.765, 0.0) [0.0, 0.7593, 0.0]
PeriodicSite: Ga (0.0, 1.828, 0.0) [0.0, 0.2407, 0.0]
PeriodicSite: Ga (2.755, 1.969, 3.17) [0.5, 0.2593, 0.5]
PeriodicSite: Ga (2.755, 5.624, 3.17) [0.5, 0.7407, 0.5]
PeriodicSite: Ga (0.0, 0.0, 0.4668) [0.0, 0.0, 0.07362]
PeriodicSite: Ga (0.0, 0.0, 5.874) [0.0, 0.0, 0.9264]
PeriodicSite: Ga (2.755, 3.796, 3.637) [0.5, 0.5, 0.5736]
Period

In [13]:
def project_lattice_to_primitive_wrapper(conv, sym_info):
    return project_lattice_to_primitive(conv.lattice.matrix, np.array(sym_info["conv_to_prim"]), sym_info["spacegroup"])


In [26]:
res["sym_info"]["conv_to_prim"]

[[-0.5, 0.5, 0.5], [0.5, -0.5, 0.5], [0.5, 0.5, -0.5]]

In [32]:
np.array(res["sym_info"]["conv_to_prim"]).dot(res["structure"].lattice.matrix)

array([[-1.21878728, -2.97421046,  2.8817794 ],
       [-3.42128049,  2.97421046,  1.62264839],
       [-1.21878728, -2.97421046, -3.58506632]])

In [15]:
project_lattice_to_primitive_wrapper(res["structure"], res["sym_info"])

array([[0.        , 4.54680061, 4.54680014],
       [4.31694555, 0.        , 4.54680014],
       [4.31694555, 4.54680061, 0.        ]])

In [20]:
res["proj_structure"].get_primitive_structure()

Structure Summary
Lattice
    abc : 7.072781932639566 7.072781932639566 7.072781932639566
 angles : 101.93479982161779 109.21506077989316 117.65112825004546
 volume : 267.20768258861386
      A : -4.454172611236572 -4.096371650695801 -3.6611924171447754
      B : 4.454172611236572 4.096371650695801 -3.6611924171447754
      C : 4.454172611236572 -4.096371650695801 3.6611924171447754
    pbc : True True True
PeriodicSite: Co (-2.227, -2.048, -1.831) [0.5, 0.0, 0.0]
PeriodicSite: Co (2.227, 2.048, -1.831) [0.0, 0.5, 0.0]
PeriodicSite: Co (2.227, -2.048, 1.831) [0.0, 0.0, 0.5]
PeriodicSite: Co (2.227, -2.048, -1.831) [0.5, 0.5, 0.5]
PeriodicSite: Co (2.22e-16, -2.279, -3.661) [0.7782, 0.5, 0.2782]
PeriodicSite: Co (4.454, -1.817, 0.0) [0.2218, 0.5, 0.7218]
PeriodicSite: Ga (4.454, 0.0, -1.791) [0.2446, 0.7446, 0.5]
PeriodicSite: Ga (4.441e-16, -4.096, -1.87) [0.7554, 0.2554, 0.5]
PeriodicSite: Ga (0.0, -1.843, 0.0) [0.225, 0.0, 0.225]
PeriodicSite: Ga (0.0, -6.349, 0.0) [0.775, 0.0, 0.775

In [28]:
SpacegroupAnalyzer(res["proj_structure"]).get_primitive_standard_structure()

Structure Summary
Lattice
    abc : 7.072781932639566 7.072781932639566 7.072781932639566
 angles : 117.65112825004546 109.21506077989316 101.93479982161779
 volume : 267.2076825886138
      A : -3.661192417144775 4.096371650695801 4.454172611236572
      B : 3.661192417144775 -4.096371650695801 4.454172611236572
      C : 3.661192417144776 4.096371650695801 -4.454172611236571
    pbc : True True True
PeriodicSite: Y (0.0, 0.0, 0.0) [0.0, 0.0, 0.0]
PeriodicSite: Ga (1.791, -2.22e-16, 4.454) [0.5, 0.7446, 0.2446]
PeriodicSite: Ga (1.87, 4.096, 4.441e-16) [0.5, 0.2554, 0.7554]
PeriodicSite: Ga (3.661, 2.253, 4.454) [0.775, 1.0, 0.775]
PeriodicSite: Ga (3.661, -2.253, 4.454) [0.225, 1.0, 0.225]
PeriodicSite: Ga (4.957, -4.441e-16, 8.882e-16) [3.407e-17, 0.6769, 0.6769]
PeriodicSite: Ga (2.366, -2.22e-16, 4.441e-16) [1.626e-17, 0.3231, 0.3231]
PeriodicSite: Co (1.831, 6.145, -2.227) [0.5, 0.0, 1.0]
PeriodicSite: Co (1.831, 2.048, 2.227) [0.5, 0.5, 0.5]
PeriodicSite: Co (1.831, 2.048, -2.22

In [29]:
SpacegroupAnalyzer(res["proj_structure"]).get_conventional_to_primitive_transformation_matrix()

array([[-0.5,  0.5,  0.5],
       [ 0.5, -0.5,  0.5],
       [ 0.5,  0.5, -0.5]])

In [14]:
map_sites_conv_to_prim(res["proj_structure"], project_lattice_to_primitive_wrapper(res["structure"], res["sym_info"]))

([Element Y,
  Element Y,
  Element Ga,
  Element Ga,
  Element Ga,
  Element Ga,
  Element Ga,
  Element Ga,
  Element Ga,
  Element Ga,
  Element Ga,
  Element Ga,
  Element Ga,
  Element Ga,
  Element Co,
  Element Co,
  Element Co,
  Element Co,
  Element Co,
  Element Co,
  Element Co,
  Element Co,
  Element Co,
  Element Co,
  Element Co,
  Element Co],
 [array([0., 0., 0.]),
  array([0.4889817 , 0.89894669, 0.87761582]),
  array([0.87893934, 0.40260432, 0.25223264]),
  array([0.73139731, 0.39528906, 0.25223264]),
  array([0.7575844 , 0.50365763, 0.62538318]),
  array([0.22037901, 0.78976622, 0.62538318]),
  array([0.41010403, 0.        , 0.86954751]),
  array([0.95752273, 0.        , 0.38121885]),
  array([0.53145897, 0.89894669, 0.49639697]),
  array([0.44650444, 0.89894669, 0.25883467]),
  array([0.21311745, 0.75691322, 0.        ]),
  array([0.3972192 , 0.53651064, 0.        ]),
  array([0.70209915, 0.65585991, 0.87761582]),
  array([0.27586425, 0.14203347, 0.87761582]),
  a

In [12]:
def map_sites_conv_to_prim(conv, prim_lattice_inv):
    new_fracs = []
    new_species = []
    for site in conv:
        new_frac = np.dot(site.coords, prim_lattice_inv)
        # if not any(partial(pbc_diff,new_frac) == partial(f) for f in new_fracs):
        #     new_species.append(site.specie)
        if not any(map(partial(is_periodic_image, new_frac), new_fracs)):
            new_fracs.append(new_frac % 1)
            new_species.append(site.specie)

    # Rhombohedral is not implemented yet
    return new_species, new_fracs


In [181]:
res["proj_structure"].frac_coords

array([[0.        , 0.        , 0.        ],
       [0.5       , 0.5       , 0.5       ],
       [0.5       , 0.        , 0.68112411],
       [0.5       , 0.        , 0.31887589],
       [0.        , 0.5       , 0.18112411],
       [0.        , 0.5       , 0.81887589],
       [0.        , 0.7592959 , 0.        ],
       [0.        , 0.2407041 , 0.        ],
       [0.5       , 0.2592959 , 0.5       ],
       [0.5       , 0.7407041 , 0.5       ],
       [0.        , 0.        , 0.07362263],
       [0.        , 0.        , 0.92637737],
       [0.5       , 0.5       , 0.57362263],
       [0.5       , 0.5       , 0.42637737],
       [0.25      , 0.25      , 0.25      ],
       [0.75      , 0.75      , 0.25      ],
       [0.75      , 0.25      , 0.75      ],
       [0.25      , 0.75      , 0.75      ],
       [0.75      , 0.75      , 0.75      ],
       [0.25      , 0.25      , 0.75      ],
       [0.25      , 0.75      , 0.25      ],
       [0.75      , 0.25      , 0.25      ],
       [0.

In [182]:
frac_1 = random.random((5,3))
frac_2 = random.random((5,3))

In [183]:
periodic_norm_frac_fixed(frac_1, frac_2)["frac_dist2"]

KeyError: 'frac_dist2'

In [127]:
conv.sites[1].coords

array([2.5189935, 4.103504 , 4.316946 ])

In [129]:
prim_lattice = prim.lattice.matrix

In [159]:
prim.lattice.inv_matrix

array([[ 2.20370363e-17,  1.98491977e-01,  1.98491977e-01],
       [ 1.21847085e-01, -2.70554878e-17,  1.21847085e-01],
       [ 1.15822621e-01,  1.15822621e-01,  0.00000000e+00]])

In [ ]:
prim_lattice_inv = np.linalg.inv(prim_lattice)

In [150]:
def is_periodic_image(frac_coords1, frac_coords2, pbc=(True, True, True), tolerance=1e-7):
    frac_diff = pbc_diff(frac_coords1, frac_coords2, pbc)
    return np.allclose(frac_diff, np.zeros_like(frac_diff), atol=tolerance)

In [156]:
new_fracs = []
new_species = []
for site in conv:
    new_frac = np.dot(site.coords, prim_lattice_inv)
    # if not any(partial(pbc_diff,new_frac) == partial(f) for f in new_fracs):
    #     new_species.append(site.specie)
    if not any(map(partial(is_periodic_image,new_frac),new_fracs)):
        new_fracs.append(new_frac % 1)
        new_species.append(site.specie)
    

In [157]:
new_fracs

[array([0., 0., 0.]),
 array([0.811228, 0.311228, 0.5     ]),
 array([0.188772, 0.688772, 0.5     ]),
 array([0.658796, 0.      , 0.658796]),
 array([0.341204, 0.      , 0.341204]),
 array([0.65413, 0.65413, 0.     ]),
 array([0.34587, 0.34587, 0.     ]),
 array([0.5, 0. , 0. ]),
 array([0. , 0.5, 0. ]),
 array([2.22044605e-16, 0.00000000e+00, 5.00000000e-01]),
 array([0.5, 0.5, 0.5]),
 array([0.23856, 0.5    , 0.73856]),
 array([0.76144, 0.5    , 0.26144])]

In [155]:
prim.frac_coords

array([[0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [8.11228000e-01, 3.11228000e-01, 5.00000000e-01],
       [1.88772000e-01, 6.88772000e-01, 5.00000000e-01],
       [6.58796000e-01, 0.00000000e+00, 6.58796000e-01],
       [3.41204000e-01, 0.00000000e+00, 3.41204000e-01],
       [6.54130000e-01, 6.54130000e-01, 0.00000000e+00],
       [3.45870000e-01, 3.45870000e-01, 0.00000000e+00],
       [5.00000000e-01, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 5.00000000e-01, 0.00000000e+00],
       [2.22044605e-16, 0.00000000e+00, 5.00000000e-01],
       [5.00000000e-01, 5.00000000e-01, 5.00000000e-01],
       [2.38560000e-01, 5.00000000e-01, 7.38560000e-01],
       [7.61440000e-01, 5.00000000e-01, 2.61440000e-01]])

In [154]:
new_species

[Element Y,
 Element Ga,
 Element Ga,
 Element Ga,
 Element Ga,
 Element Ga,
 Element Ga,
 Element Co,
 Element Co,
 Element Co,
 Element Co,
 Element Co,
 Element Co]

In [145]:
new_fracs[0]

array([0., 0., 0.])

In [134]:
new_fracs

[array([0., 0., 0.]),
 array([1., 1., 1.]),
 array([0.811228, 1.311228, 0.5     ]),
 array([0.188772, 0.688772, 0.5     ]),
 array([0.658796, 1.      , 0.658796]),
 array([1.341204, 1.      , 1.341204]),
 array([0.65413, 0.65413, 0.     ]),
 array([0.34587, 0.34587, 0.     ]),
 array([0.811228, 0.311228, 0.5     ]),
 array([1.188772, 0.688772, 0.5     ]),
 array([6.58796000e-01, 6.46459876e-17, 6.58796000e-01]),
 array([3.41204000e-01, 3.34814868e-17, 3.41204000e-01]),
 array([0.65413, 0.65413, 1.     ]),
 array([1.34587, 1.34587, 1.     ]),
 array([0.5, 1. , 1. ]),
 array([1. , 0.5, 1. ]),
 array([1. , 1. , 1.5]),
 array([0.5, 0.5, 0.5]),
 array([1.23856, 0.5    , 0.73856]),
 array([0.76144, 0.5    , 0.26144]),
 array([1.5, 1. , 1. ]),
 array([1. , 1.5, 1. ]),
 array([1. , 1. , 0.5]),
 array([1.5, 1.5, 1.5]),
 array([0.23856, 0.5    , 0.73856]),
 array([0.76144, 0.5    , 1.26144])]

In [135]:
pbc_diff(new_fracs[0], new_fracs[1])          

array([0., 0., 0.])

In [28]:
res["proj_structure"].frac_coords[-5:]

array([[0.75      , 0.25      , 0.25      ],
       [0.        , 0.13559833, 0.5       ],
       [0.        , 0.86440167, 0.5       ],
       [0.5       , 0.63559833, 0.        ],
       [0.5       , 0.36440167, 0.        ]])

In [28]:
st.species

[Element Y,
 Element Ga,
 Element Ga,
 Element Ga,
 Element Ga,
 Element Ga,
 Element Ga,
 Element Co,
 Element Co,
 Element Co,
 Element Co,
 Element Co,
 Element Co]

In [53]:
st.species

13

In [26]:
res[0].species

[Element Y,
 Element Y,
 Element Ga,
 Element Ga,
 Element Ga,
 Element Ga,
 Element Ga,
 Element Ga,
 Element Ga,
 Element Ga,
 Element Ga,
 Element Ga,
 Element Ga,
 Element Ga,
 Element Co,
 Element Co,
 Element Co,
 Element Co,
 Element Co,
 Element Co,
 Element Co,
 Element Co,
 Element Co,
 Element Co,
 Element Co,
 Element Co]

In [29]:
frac = prim.lattice.get_fractional_coords(res[0].cart_coords)

In [167]:
SpacegroupAnalyzer(conv).get_symmetrized_structure()

SymmetrizedStructure
Full Formula (Y2 Ga12 Co12)
Reduced Formula: Y(GaCo)6
Spacegroup: Immm (71)
abc   :   5.037987   8.207008   8.633892
angles:  90.000000  90.000000  90.000000
Sites (26)
  #  SP       a         b         c  Wyckoff
---  ----  ----  --------  --------  ---------
  0  Y     0     0         0         2a
  1  Ga    0.5   0         0.811228  4j
  2  Ga    0.5   0.158796  0.5       4g
  3  Ga    0     0         0.65413   4i
  4  Co    0.75  0.25      0.25      8k
  5  Co    0     0.73856   0.5       4h

In [168]:
print('Primitive')
print(prim.lattice)
print("Conventional")
print(conv.lattice)
print("Transformed")
print(np.dot(conv_to_prim, conv.lattice.matrix))
print("inverse transformed")
print(np.dot(np.linalg.inv(conv_to_prim), prim.lattice.matrix))

Primitive
-2.518993 4.103504 4.316946
2.518993 -4.103504 4.316946
2.518994 4.103504 -4.316946
Conventional
5.037987 0.000000 0.000000
0.000000 8.207008 0.000000
0.000000 0.000000 8.633892
Transformed
[[-2.5189935  4.103504   4.316946 ]
 [ 2.5189935 -4.103504   4.316946 ]
 [ 2.5189935  4.103504  -4.316946 ]]
inverse transformed
[[5.0379870e+00 0.0000000e+00 0.0000000e+00]
 [8.8817842e-16 8.2070080e+00 0.0000000e+00]
 [0.0000000e+00 0.0000000e+00 8.6338920e+00]]


In [169]:
def project_lattice(lattice, spacegroup):
    if isinstance(lattice, Lattice):
        mat = torch.Tensor(lattice.matrix.copy()).unsqueeze(0)
    elif isinstance(lattice, torch.Tensor):
        assert lattice.shape == (1, 3, 3) or lattice.shape == (3, 3)
        if lattice.shape == (3, 3):
            lattice = lattice.unsqueeze(0)
        mat = lattice
    elif isinstance(lattice, np.ndarray):
        assert lattice.shape == (1, 3, 3) or lattice.shape == (3, 3)
        if lattice.shape == (3, 3):
            lattice = lattice[np.newaxis, ...]
        mat = torch.Tensor(lattice.copy())

    cf = symmetry_utils.CrystalFamily()
    # mat = torch.Tensor(lattice.matrix.copy()).unsqueeze(0)
    mat2 = cf.de_so3(mat)
    vec = cf.m2v(mat2)
    proj_vec = cf.proj_k_to_spacegroup(vec, spacegroup)
    proj_mat = cf.v2m(proj_vec)
    lattice = Lattice(proj_mat[0].numpy())
    return lattice

In [170]:
rand_lat = initialize_random_lattice()
rand_lat

Lattice
    abc : 6.103951123685148 6.953173976866979 5.005067160698854
 angles : 62.459766575432276 103.1495549547993 73.72011359645384
 volume : 164.11758814665836
      A : 5.943902918530505 0.0 -1.3886098859729203
      B : 2.7527398125401246 5.516625582239972 3.214948531844982
      C : 0.0 0.0 5.005067160698854
    pbc : True True True

In [171]:
# rand_lat

In [172]:
Lattice(project_lattice_to_primitive(rand_lat.matrix,conv_to_prim,tt.get_space_group_number()))

Lattice
    abc : 6.017001936283774 7.576836062890358 6.128490640592566
 angles : 50.74702699341752 77.18804833085375 52.06492467572875
 volume : 164.11771397292992
      A : 0.0 2.8595685958862305 5.294070243835449
      B : 5.4204487800598145 0.0 5.294070243835449
      C : 5.4204487800598145 2.8595685958862305 0.0
    pbc : True True True

In [173]:
prim

Structure Summary
Lattice
    abc : 6.466845915030855 6.466845915030855 6.466845915030855
 angles : 134.15019606860565 101.22752473560247 96.24342222845507
 volume : 178.49190115630992
      A : -2.5189934999999997 4.103503999710353 4.316945999207094
      B : 2.5189934999999997 -4.103503999710353 4.316945999207094
      C : 2.5189935000000006 4.103503999710353 -4.316945999207094
    pbc : True True True
PeriodicSite: Y (0.0, 0.0, 0.0) [0.0, 0.0, 0.0]
PeriodicSite: Ga (6.661e-16, 4.104, 2.687) [0.8112, 0.3112, 0.5]
PeriodicSite: Ga (2.519, 4.441e-16, 1.63) [0.1888, 0.6888, 0.5]
PeriodicSite: Ga (4.441e-16, 5.407, 0.0) [0.6588, 0.0, 0.6588]
PeriodicSite: Ga (3.331e-16, 2.8, 0.0) [0.3412, 0.0, 0.3412]
PeriodicSite: Ga (0.0, 0.0, 5.648) [0.6541, 0.6541, 0.0]
PeriodicSite: Ga (0.0, 0.0, 2.986) [0.3459, 0.3459, 0.0]
PeriodicSite: Co (-1.259, 2.052, 2.158) [0.5, 0.0, 0.0]
PeriodicSite: Co (1.259, -2.052, 2.158) [0.0, 0.5, 0.0]
PeriodicSite: Co (1.259, 2.052, -2.158) [2.22e-16, 0.0, 0.5]
Peri

In [174]:
def prim_coords_to_conv_coords(frac_coords, prim_lat, conv_lat,use_is_close=True):
    res = conv_lat.get_fractional_coords(prim_lat.get_cartesian_coords(frac_coords))
    if use_is_close:
        res[np.isclose(res,np.zeros_like(res))] = 0
    return res

In [175]:
res = prim_coords_to_conv_coords(prim.frac_coords,prim.lattice,conv.lattice)

In [176]:
sd.__dir__()

['number',
 'hall_number',
 'international',
 'hall',
 'choice',
 'transformation_matrix',
 'origin_shift',
 'rotations',
 'translations',
 'wyckoffs',
 'site_symmetry_symbols',
 'crystallographic_orbits',
 'equivalent_atoms',
 'primitive_lattice',
 'mapping_to_primitive',
 'std_lattice',
 'std_positions',
 'std_types',
 'std_rotation_matrix',
 'std_mapping_to_primitive',
 'pointgroup',
 '__module__',
 '__annotations__',
 '__doc__',
 '__abstractmethods__',
 '_abc_impl',
 '__dataclass_params__',
 '__dataclass_fields__',
 '__init__',
 '__repr__',
 '__setattr__',
 '__delattr__',
 '__match_args__',
 '__getitem__',
 '__len__',
 '__iter__',
 '__orig_bases__',
 '__dict__',
 '__weakref__',
 '__eq__',
 '__hash__',
 '__slots__',
 'get',
 '__contains__',
 'keys',
 'items',
 'values',
 '__reversed__',
 '__subclasshook__',
 '__new__',
 '__str__',
 '__getattribute__',
 '__lt__',
 '__le__',
 '__ne__',
 '__gt__',
 '__ge__',
 '__reduce_ex__',
 '__reduce__',
 '__init_subclass__',
 '__format__',
 '__size

In [177]:
sd.crystallographic_orbits

array([ 0,  1,  1,  3,  3,  5,  5,  7,  7,  7,  7, 11, 11], dtype=int32)

In [178]:
sd.equivalent_atoms

array([ 0,  1,  1,  3,  3,  5,  5,  7,  7,  7,  7, 11, 11], dtype=int32)

In [179]:
res

array([[ 0.      ,  0.      ,  0.      ],
       [ 0.      ,  0.5     ,  0.311228],
       [ 0.5     ,  0.      ,  0.188772],
       [ 0.      ,  0.658796,  0.      ],
       [ 0.      ,  0.341204,  0.      ],
       [ 0.      ,  0.      ,  0.65413 ],
       [ 0.      ,  0.      ,  0.34587 ],
       [-0.25    ,  0.25    ,  0.25    ],
       [ 0.25    , -0.25    ,  0.25    ],
       [ 0.25    ,  0.25    , -0.25    ],
       [ 0.25    ,  0.25    ,  0.25    ],
       [ 0.5     ,  0.23856 ,  0.      ],
       [ 0.      ,  0.26144 ,  0.5     ]])

In [180]:
prim.cart_coords

array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 6.66133815e-16,  4.10350400e+00,  2.68710894e+00],
       [ 2.51899350e+00,  4.44089210e-16,  1.62983706e+00],
       [ 4.44089210e-16,  5.40674404e+00,  0.00000000e+00],
       [ 3.33066907e-16,  2.80026396e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  5.64768777e+00],
       [ 0.00000000e+00,  0.00000000e+00,  2.98620423e+00],
       [-1.25949675e+00,  2.05175200e+00,  2.15847300e+00],
       [ 1.25949675e+00, -2.05175200e+00,  2.15847300e+00],
       [ 1.25949675e+00,  2.05175200e+00, -2.15847300e+00],
       [ 1.25949675e+00,  2.05175200e+00,  2.15847300e+00],
       [ 2.51899350e+00,  1.95786383e+00, -4.44089210e-16],
       [ 3.33066907e-16,  2.14564017e+00,  4.31694600e+00]])

In [181]:
conv.lattice.get_fractional_coords(prim.cart_coords)

array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 1.23859833e-18,  5.00000000e-01,  3.11228000e-01],
       [ 5.00000000e-01,  5.41109756e-17,  1.88772000e-01],
       [-8.44348240e-17,  6.58796000e-01, -3.83451159e-17],
       [-2.32731609e-17,  3.41204000e-01, -1.98597243e-17],
       [ 0.00000000e+00,  0.00000000e+00,  6.54130000e-01],
       [ 0.00000000e+00,  0.00000000e+00,  3.45870000e-01],
       [-2.50000000e-01,  2.50000000e-01,  2.50000000e-01],
       [ 2.50000000e-01, -2.50000000e-01,  2.50000000e-01],
       [ 2.50000000e-01,  2.50000000e-01, -2.50000000e-01],
       [ 2.50000000e-01,  2.50000000e-01,  2.50000000e-01],
       [ 5.00000000e-01,  2.38560000e-01, -8.31858517e-17],
       [-2.37760605e-18,  2.61440000e-01,  5.00000000e-01]])

In [182]:
conv.frac_coords[[0,8,3,10,11,6,7,14,15,22,17,24,19]]

array([[0.      , 0.      , 0.      ],
       [0.      , 0.5     , 0.311228],
       [0.5     , 0.      , 0.188772],
       [0.      , 0.658796, 0.      ],
       [0.      , 0.341204, 0.      ],
       [0.      , 0.      , 0.65413 ],
       [0.      , 0.      , 0.34587 ],
       [0.75    , 0.25    , 0.25    ],
       [0.25    , 0.75    , 0.25    ],
       [0.25    , 0.25    , 0.75    ],
       [0.25    , 0.25    , 0.25    ],
       [0.5     , 0.23856 , 0.      ],
       [0.      , 0.26144 , 0.5     ]])

In [183]:
for num,idx in enumerate([0,8,3,10,11,6,7,14,15,22,17,24,19]):
    print(idx, conv.frac_coords[idx], prim.cart_coords[num], conv.species[idx], prim.species[num])

0 [0. 0. 0.] [0. 0. 0.] Y Y
8 [0.       0.5      0.311228] [6.66133815e-16 4.10350400e+00 2.68710894e+00] Ga Ga
3 [0.5      0.       0.188772] [2.51899350e+00 4.44089210e-16 1.62983706e+00] Ga Ga
10 [0.       0.658796 0.      ] [4.44089210e-16 5.40674404e+00 0.00000000e+00] Ga Ga
11 [0.       0.341204 0.      ] [3.33066907e-16 2.80026396e+00 0.00000000e+00] Ga Ga
6 [0.      0.      0.65413] [0.         0.         5.64768777] Ga Ga
7 [0.      0.      0.34587] [0.         0.         2.98620423] Ga Ga
14 [0.75 0.25 0.25] [-1.25949675  2.051752    2.158473  ] Co Co
15 [0.25 0.75 0.25] [ 1.25949675 -2.051752    2.158473  ] Co Co
22 [0.25 0.25 0.75] [ 1.25949675  2.051752   -2.158473  ] Co Co
17 [0.25 0.25 0.25] [1.25949675 2.051752   2.158473  ] Co Co
24 [0.5     0.23856 0.     ] [ 2.51899350e+00  1.95786383e+00 -4.44089210e-16] Co Co
19 [0.      0.26144 0.5    ] [3.33066907e-16 2.14564017e+00 4.31694600e+00] Co Co


In [184]:
for i in range(conv.frac_coords.shape[0]):
    print(i,conv.frac_coords[i])

0 [0. 0. 0.]
1 [0.5 0.5 0.5]
2 [0.5      0.       0.811228]
3 [0.5      0.       0.188772]
4 [0.5      0.158796 0.5     ]
5 [0.5      0.841204 0.5     ]
6 [0.      0.      0.65413]
7 [0.      0.      0.34587]
8 [0.       0.5      0.311228]
9 [0.       0.5      0.688772]
10 [0.       0.658796 0.      ]
11 [0.       0.341204 0.      ]
12 [0.5     0.5     0.15413]
13 [0.5     0.5     0.84587]
14 [0.75 0.25 0.25]
15 [0.25 0.75 0.25]
16 [0.75 0.75 0.25]
17 [0.25 0.25 0.25]
18 [0.      0.73856 0.5    ]
19 [0.      0.26144 0.5    ]
20 [0.25 0.75 0.75]
21 [0.75 0.25 0.75]
22 [0.25 0.25 0.75]
23 [0.75 0.75 0.75]
24 [0.5     0.23856 0.     ]
25 [0.5     0.76144 0.     ]


In [185]:
conv

Structure Summary
Lattice
    abc : 5.037987 8.207007999420705 8.633891998414189
 angles : 90.0 90.0 90.0
 volume : 356.98380231261984
      A : 5.037987 0.0 3.0848773268479883e-16
      B : 1.3197875449945775e-15 8.207007999420705 5.025343038533645e-16
      C : 0.0 0.0 8.633891998414189
    pbc : True True True
PeriodicSite: Y (0.0, 0.0, 0.0) [0.0, 0.0, 0.0]
PeriodicSite: Y (2.519, 4.104, 4.317) [0.5, 0.5, 0.5]
PeriodicSite: Ga (2.519, 0.0, 7.004) [0.5, 0.0, 0.8112]
PeriodicSite: Ga (2.519, 0.0, 1.63) [0.5, 0.0, 0.1888]
PeriodicSite: Ga (2.519, 1.303, 4.317) [0.5, 0.1588, 0.5]
PeriodicSite: Ga (2.519, 6.904, 4.317) [0.5, 0.8412, 0.5]
PeriodicSite: Ga (0.0, 0.0, 5.648) [0.0, 0.0, 0.6541]
PeriodicSite: Ga (0.0, 0.0, 2.986) [0.0, 0.0, 0.3459]
PeriodicSite: Ga (6.599e-16, 4.104, 2.687) [0.0, 0.5, 0.3112]
PeriodicSite: Ga (6.599e-16, 4.104, 5.947) [0.0, 0.5, 0.6888]
PeriodicSite: Ga (8.695e-16, 5.407, 3.311e-16) [0.0, 0.6588, 0.0]
PeriodicSite: Ga (4.503e-16, 2.8, 1.715e-16) [0.0, 0.3412,

In [186]:
def periodic_norm_frac(a, b):
    mirror = [(i, j, k) for i in [-1, 0, 1] for j in [-1, 0, 1] for k in [-1, 0, 1]]
    mirror = np.array(mirror).reshape(-1, 1, 3)
    a = np.array(a)
    b = np.array(b)
    b_mirror = b.reshape(1, -1, 3) + mirror
    dist = np.linalg.norm(
        a.reshape(1, 1, -1, 3).repeat(27, axis=0) - b_mirror.reshape(27, -1, 1, 3), axis=3
    )
    dist_min = np.min(dist, axis=0)
    dist_argmin = dist.argmin(axis=0)
    row_indices, col_indices = linear_sum_assignment(dist_min)
    return {
        "distances": dist_min[row_indices, col_indices],
        "indices": np.stack([row_indices, col_indices]),
        "target_pos": b_mirror[dist_argmin[row_indices, col_indices], col_indices],
    }